### ISSUE TITLE
Refreshing WebElement/WebComponent list

### ISSUE THREAD

**Issue by EbisuGit** [webdriverextensions/webdriverextensions#113]
Can I somehow refresh List<WebElement> / WebComponentList after new DOM element/component meets @FindBy criteria applied to the list?

Let's say I have 3 elements that meet the criteria of @FindBy, I can iterate over them and use just fine, but when 4th element is added to page and meets the criteria, trying to iterate over elements throws:
`The element reference of <div class="someComponentClass"> stale: either the element is no longer attached to the DOM or the page has been refreshed
`
Right now I can resolve this by calling `Bot.nagivateRefresh()`, but it's not always possible as page can have temporary content that requires saving or similar situations, plus refreshing whole page might be slow in some cases.

**Comment by EbisuGit** [comment]
Somehow I can't reproduce it anymore. That's strange because when I tested it before posting the issue it occurred to me every single time. I don't have access to page I was testing it on anymore, but it was Apache Wicked-based. If it occurs again I'll make sure to create a concrete scenario.

**Comment by andidev** [comment]
Okej so I'll close this issue then.
