### ISSUE TITLE
Incorrect element scan inside WebComponent

### ISSUE THREAD

**Issue by EbisuGit** [webdriverextensions/webdriverextensions#114]
The problem occurs then, inside WebComponent `@FindBy(xpath = "//...")` is used. Unfortunately, global scan is performed, and f.e. having 10 components on page, element found by `"//..."` is always the same element. Temporary solution is to not use `"//"` at all if element is direct child of component, or use `"*//..."` if it's not, but it's inconsistent and requires additional attention.

**Comment by andidev** [comment]
I have no xpath skills here so maybe what I am about to say does not make sense =)
Does this issue also occur when annotating a normal WebElement? I think this may be more of a Selenium issue. WebComponent simply wraps a WebElement with the WebElement as a search context.

**Comment by EbisuGit** [comment]
Here is an example:
```java
public class IssueTest {

    /* random component for storing h3 elements */
    public static class AnyList extends WebComponent {

        @FindBy(xpath = "//h3")
        public List<WebElement> headers;

    }

    /* first column of w3schools example list, should contain only "HTML and CSS" */
    @FindBy(css = "#nav_examples > div:nth-child(3) > div:nth-child(1)")
    AnyList firstColumn;

    /* second column of w3schools example list, should contain only "JavaScript" */
    @FindBy(css = "#nav_examples > div:nth-child(3) > div:nth-child(2)")
    AnyList secondColumn;

    /* utility button for navigating to example page (dynamic content, not important for issue) */
    @FindBy(css = "#navbtn_examples")
    WebElement examplesButton;
    
    public IssueTest(WebDriver driver) {
        PageFactory.initElements(new WebDriverExtensionFieldDecorator(driver), this);
    }

    public static void main(String[] args) {

        DriverPathLoader.loadDriverPaths(null); // default drivers path
        WebDriverExtensionsContext.setDriver(new FirefoxDriver()); // set driver in context
        
        IssueTest issueTest = new IssueTest(driver()); // create object and init fields
        open("https://www.w3schools.com/"); // open page
        click(issueTest.examplesButton); // and navigate to examples
        
        // first column
        System.out.println("First column headers:");
        issueTest.firstColumn.headers.forEach((elem) -> {
            System.out.println(textIn(elem));
        });

        // second column
        System.out.println("\nSecond column headers:");
        issueTest.secondColumn.headers.forEach((elem) -> {
            System.out.println(textIn(elem));
        });
    }

}
```
And the output is:

> **First column headers:**
> HTML and CSS
> JavaScript
> XML
> Server Side
> Quizzes
> HTML Example:
> CSS Example:
> JavaScript Example:
> Get Certified in HTML, CSS, and JavaScript
> 
> **Second column headers:**
> HTML and CSS
> JavaScript
> XML
> Server Side
> Quizzes
> HTML Example:
> CSS Example:
> JavaScript Example:
> Get Certified in HTML, CSS, and JavaScript

It fetches all elements on page that can be found by `//h3` xpath. If we called `.findElements()` on `WebElement` object instead, it would have expected result of one `h3` element per list. 

Saying all that, I don't know if it's WebDriverExtensions or Selenium issue.

**Comment by andidev** [comment]
> It fetches all elements on page that can be found by //h3 xpath. If we called .findElements() on WebElement object instead, it would have expected result of one h3 element per list.

I just added the following to the model
```java
    @FindBy(css = "#navbtn_examples")
    WebElement examplesButton;
```

...and then used `findElements(By.xpath("//h3"))`
```java
        System.out.println("First column headers with webelement:");
        issueTest.firstColumnByWebElement.findElements(By.xpath("//h3")).forEach((elem) -> {
            System.out.println(textIn(elem));
        });
```
...and got the same result. Are you sure this is not the expected behaviour? Also according to the docs at w3schools this is the expected behaviour when using `//`, see https://www.w3schools.com/xml/xpath_syntax.asp

**Comment by chamacs** [comment]
The correct syntax for the xpath would be to use .// (start with a period).  The search will use the WebComponent element as the root of the search.
```
public static class AnyList extends WebComponent {

        @FindBy(xpath = ".//h3")
        public List<WebElement> headers;

 }
```

**Comment by EbisuGit** [comment]
You are right. I somehow took for granted that parent element is absolute root in search context, but it's not. My bad. Issue can be closed.
