### ISSUE TITLE
Question: how to get underlying WebElement from WebComponent?

### ISSUE THREAD

**Issue by ashoofly** [webdriverextensions/webdriverextensions#116]
I can get a child element of a WebComponent by using `findElement(By by)`, but is there a way to access the wrapped WebElement of the WebComponent? I initialized it using `PageFactory.initElements(new WebDriverExtensionFieldDecorator(webDriver), this)`.

**Comment by ashoofly** [comment]
Oh, would it just be `this`?

**Comment by andidev** [comment]
The [wrappedWebElement](https://github.com/webdriverextensions/webdriverextensions/blob/master/src/main/java/com/github/webdriverextensions/WebComponent.java#L10) in a WebComponent seems to be package private and therefore not available when extending the WebComponent. This could easily be changed by making it protected och adding a getter.

What is the use case for accessing it?

**Comment by andidev** [comment]
Released in version 3.8.1
