### ISSUE TITLE
Spring Injection/ApplicationContext

### ISSUE THREAD

**Issue by Ismoh** [webdriverextensions/webdriverextensions#122]
Hey there,
I am new to Spring and want to know whether I can use Spring annotations in my selenium test module.

I am not really familiar with the correct names of Spring, but I found out that webdriver extensions use the @RunWith(WebDriverRunner.class). Spring is running with the SpringRunner.class.

Atm I want to use a different class from the site module to use a translation method.

Is there a good way to combine the WebDriverRunner with the SpringRunner?
Or do I have simply bad luck and I am not able to use Spring stuff in the selenium tests?

I would be very pleased to receive suggestions.
Thanks, Ismoh

**Comment by andidev** [comment]
I don't think you should use the WebDriverRunner in combination with the SpringRunner. Maybe you could create a `new MockMvcHtmlUnitDriver()` and then init your components with `PageFactory.initElements(new WebDriverExtensionFieldDecorator(yourDriver), this);` in the `@Before` annotated setup method.

see https://spring.io/blog/2014/03/26/spring-mvc-test-with-webdriver#initializing-webdriver

Another option is maybe to use the WebDriverRunner and then programatically start your spring application with `SpringApplication.run(Application.class)` in a @BeforeClass annotated method. Most probably this will take a while to start and it feels like this is not the right way to do it =)

**Comment by Ismoh** [comment]
If I use `new MockMvcHtmlUnitDriver()`, am I still able to use the web driver extensions annotations, etc. ?
I guess not and that's quite bad, because I already set up the webdriver stuff on my own and that wasn't quite nice as your web driver extension stuff. I'll have a look and add something, if I found another way.
Thanks for your reply! :+1:

**Comment by andidev** [comment]
Depends on what annotations you mean. The WebDriverRunner specific annotation won't work, e.g. @Firefox, @Chrome though if you use WebDriverExtensionFieldDecorator as I told you you could still use the @WebComponent, @WebRepository annotations, etc. You could also still use the Bot methods if you set the driver in the WebDriverExtensionsContext

**Comment by Ismoh** [comment]
I am currently using your WebdriverExtensionRunner and I am injecting Spring on a nother way.
