### ISSUE TITLE
Yandex or YaBrowser support?

### ISSUE THREAD

**Issue by Ismoh** [webdriverextensions/webdriverextensions#123]
Is there any opportunity to add the russian YaBrowser (https://browser.yandex.com/) from Yandex?
We have a bunch of customers from russia, therefore we want to test our website on YaBrowser as well.
I guess since there is no YaBrowser driver, this won't work, doesn't it ?
Kind regards Ismoh & thanks for the reply.

**Comment by andidev** [comment]
Does selenium support YaBrowser testing?

**Comment by Ismoh** [comment]
I guess not, but I found this one:
https://stackoverflow.com/questions/30707783/java-selenium-webdriver-with-yandex

I do not need this anymore, therefore I close this ticket.
Thanks anyways :)
