### ISSUE TITLE
IllegalArgumentException: Argument is of an illegal type X when using ExpectedConditions.visibilityOf

### ISSUE THREAD

**Issue by javydreamercsw** [webdriverextensions/webdriverextensions#128]
I have a WebComponent that works as expected but It's failing when I try to use something like ExpectedConditions.visibilityOf.

Might be related to #111.

**Comment by andidev** [comment]
@javydreamercsw 
This should work, tested it with the latest release, could you try the latest release 3.11.0?

If you still have the issue could you provide a more specific sample of how to reproduce?

**Comment by javydreamercsw** [comment]
Seems to work fine now. Thanks!
