### ISSUE TITLE
Bundled htmlunit cant resolve Locatable

### ISSUE THREAD

**Issue by dimkin-eu** [webdriverextensions/webdriverextensions#129]
I am using webdriverextensions 3.10.0
after updating to latest stable selenium-java  (3.141.59) getting error in runtime
```Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.internal.Locatable``` 

this is caused by bundled 
```        <htmlunit-driver.version>2.29.0</htmlunit-driver.version>```

failing class - HtmlUnitWebElement

breaking changes are introduced in selenium-java 3.141.0
with the removal of HtmlUnit probably

**Comment by dimkin-eu** [comment]
could be solved by https://github.com/webdriverextensions/webdriverextensions/pull/126

**Comment by andidev** [comment]
Yeah sorry about this. I'm gonna try to update the dependencies asap

**Comment by andidev** [comment]
@dimkin-eu new version 3.11.0 is now released and uses the latest html unit driver. Closing this. please reopen if you still have any issues.

**Comment by dimkin-eu** [comment]
@andidev , it works, thank You :)
