### ISSUE TITLE
Chrome browser windows remain open

### ISSUE THREAD

**Issue by cplaetzinger** [webdriverextensions/webdriverextensions#53]
I'm using webdriver extensions to execute the tests remotely using a selenium grid. Unfortunately the chrome browser windows remain open after the test methods are executed. This a new driver instance is created for every test method I end up with a huge amount of browser windows. I fixed this by manually calling the close method
```
@After
public void shutdown(){
	final WebDriver driver = Bot.driver();
	if (driver != null) {
		driver.close();
	}
}
```
I'm wondering if something in my setu is broken or if the WebDriverRunner should call the drivers close method. Any thoughts?

**Comment by andidev** [comment]
I need to have a look at this. It should be closed automatically. Maybe there is some error occurring that is not handled. Is there any sign of an error? Any stacktrace?

**Comment by cplaetzinger** [comment]
Unfortunately not. Will do some debugging tomorrow.

**Comment by andidev** [comment]
That would be great. The code is a bit messy but this is where where the driver is closed:

[WebDriverRunner.java line 278](https://github.com/webdriverextensions/webdriverextensions/blob/master/src/main/java/com/github/webdriverextensions/junitrunner/WebDriverRunner.java#L278) 

Set a breakpoint in this method and see if it exits before the driver quit call for some reason.

**Comment by andidev** [comment]
@cplaetzinger 
Any progress on the debugging?

**Comment by andidev** [comment]
I've just tested this and the driver.quit() is called remotely when test result is sucess and failed.

Closing this until you provide more feedback on how to reproduce.

Maybe you are using old drivers in your selenium grid?
