### ISSUE TITLE
Can't extend Bot anymore

### ISSUE THREAD

**Issue by dve** [webdriverextensions/webdriverextensions#63]
We used our on implementation of [Bot](src/main/java/com/github/webdriverextensions/Bot.java) which extends Bot to have support for the vaadin webframework. Since the constructor of  [Bot](src/main/java/com/github/webdriverextensions/Bot.java) is private since 672d99a36808fb738895538419f3b122867f5d4b this does not work in 2.6.0 any more. Can the constructor become public again?

**Comment by andidev** [comment]
Yes no problem.I'll try to release a fix for it before the end of this week.

**Comment by dve** [comment]
Thanks, that would be great

**Comment by andidev** [comment]
So it's done and released in version 2.6.1 to Sonatype nexus repo and will be available in the official maven repo in a couple of hours.

**Comment by dve** [comment]
Thanks for the fast fix. Are you interested in a pull request with the VaadinBot, or is this not the right place for framework specific stuff? The Bot contains some vaadin specific wait stuff.

**Comment by andidev** [comment]
@dve 
Not familiar with the Vaadin framework but I'm willing to add it if it does not require adding any external framework specific maven dependency. Please create a PR and I'll review it and merge it.
