### ISSUE TITLE
Safari webdriver 

### ISSUE THREAD

**Issue by KseniaBudlianska** [webdriverextensions/webdriverextensions#65]
Hi, could you please tell me can I add somehow safari driver for mac platform using your webdriverextensions?
Best regards,
Ksenia

**Comment by andidev** [comment]
Not 100% sure about this but isnt't the safari driver the same as the chromedriver?

If not please give me the url to the download location and I'll try to add it to the repo.

**Comment by KseniaBudlianska** [comment]
Yes, it's totally working in different way. You need to download extension to the Safari browser for using it. At the same time I failed to connect with Safari browser due to issue #7133.

After a thorough investigation I can say that Safari WebDriver is already deprecated and gives more problems for user than benefits.

So, topic could be closed.
