### ISSUE TITLE
Wrong screenshot filename on Windows platform.

### ISSUE THREAD

**Issue by consulbit** [webdriverextensions/webdriverextensions#67]
I'm using the **TakeScreenshotOnFailure** annotation and I'm experiencing a problem on Windows 10 due to the fact the filename contains a colon in it.

The message error is: Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect.

The problem is in the WebDriverRunner class at line 251 and the line pointing to the problem is the follow:
**String fileName = className + "." + methodName + "-" + getCurrentDateAndTime();**

The **getCurrentDateAndTime** generates a date with the following format: **2016-09-14T09:20** and the colon is a not an accepted character for filename in Windows.

Please remove the method call or change its format.

Regards

**Comment by andidev** [comment]
Thanx, I'll release this right away

**Comment by andidev** [comment]
So it's merged and released in version 2.8.1
Should be in maven repo within 12 hours
