### ISSUE TITLE
BotSauceLabsTest.browserIsAndroidTest() fails

### ISSUE THREAD

**Issue by dve** [webdriverextensions/webdriverextensions#79]
I'm trying to get webderiverextensions build on travis-ci, during that I found out that `com.github.webdriverextensions.BotSauceLabsTest.browserIsAndroidTest()` is failing. The sauceLabs android seems to be chrome.

**Comment by andidev** [comment]
Yes probably saucelabs can't be trusted. I think the test needs to be overseen. Please feel free to remove tests or ignore them. Or look into it and figure out what's wrong.

**Comment by dve** [comment]
I'm not testing on mobile devices, so I'm not sure, but isn't chrome the "new" default browser on android?

**Comment by andidev** [comment]
Yes looks like it so [since android 4.0](http://androidandme.com/2012/02/applications/goodbye-old-browser-chrome-to-become-the-standard-browser-on-android-4-0-and-above/) I'll go ahead and change the test to assert for chrome instead.
