### ISSUE TITLE
Update Selenium version

### ISSUE THREAD

**Issue by AmbroZary** [webdriverextensions/webdriverextensions#87]
Selenium version is out of date. Please update it.

**Comment by andidev** [comment]
I'll do It right away

**Comment by andidev** [comment]
So I had som issues with gpg signing but they where solved just now. The new release version 3.5.0 will be available in a couple of hours in the maven repo.

In the future you can always override an old selenium version in webdriverextension by adding the new selenium version as a dependency, e.g.
```
    <dependencies>
        <dependency>
            <groupId>com.github.webdriverextensions</groupId>
            <artifactId>webdriverextensions</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.4.0</version>
        </dependency>
    </dependencies>
```
