### ISSUE TITLE
Support surefire.rerunFailingTestsCount parameter

### ISSUE THREAD

**Issue by jansohn** [webdriverextensions/webdriverextensions#97]
It seems that currently the parameter `rerunFailingTestsCount` for the `maven-surefire-plugin` is not supported, correct? It is used to re-run a test if it has failed the first time.

    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${maven-surefire-plugin-version}</version>
        <configuration>
            <includes>
                <include>**/*Test.java</include>
                <include>**/*TestCase.java</include>
            </includes>
            <rerunFailingTestsCount>2</rerunFailingTestsCount>
        </configuration>
    </plugin>

I'm always getting `No runnable tests` for the second run.

    Results :
    
    Tests in error:
      MainPageTest.searchMaterialTest@InternetExplorer ? NoSuchSession Unexpected er...
    org.junit.runner.manipulation.Filter.initializationError(org.junit.runner.manipulation.Filter)
      Run 1: Filter.initializationError ?  No tests found matching Method searchMaterialTes...
      Run 2: Filter.initializationError ?  No runnable methods

Any chance this might be supported in a future release?

**Comment by andidev** [comment]
I'm not sure how surefire works and tries to rerun tests. Maybe custom runners that create multiple tests from one test method is not supported. Needs to be investigated.

**Comment by Snipx** [comment]
Hi @andidev! I faced the same issue. Due to the code organization in `WebDriverRunner`, I did not found a way to fix the issue by simply subclassing `WebDriverRunner`, so I would appreciate if you could review the pull request soon because no easy work around available.
