### ISSUE TITLE
IE is randomly getting hang while debugging, particularly click event 

### ISSUE THREAD

**Issue by ramkumary** [webdriverextensions/webdriverextensions#98]
Sometimes IE is getting hung/frozen while debugging particularly with click event.  The issue is disappeared when I terminate the IE server instance. I am not sure about this behavior.
Alternatives Tried.

a) Use SendKeys
b) Use Actions Class click

However, none of the above solutions resolved the issue. any insight on this?

Thanks,
RKY

**Comment by andidev** [comment]
This is a selenium issue so please post it in the selenium github repo.

**Comment by andidev** [comment]
Have you tried searching for this issue? Most probably this is a known issue.
