### ISSUE TITLE
Edge driver can't find file /drivers/edgedriver-windows-64bit 

### ISSUE THREAD

**Issue by miskoala** [webdriverextensions/webdriverextensions#99]
In Win10 64bit can't run tests on MS Edge.
DrivePathLoader.java:

    private static String getEdgeDefaultPath() {
        if (OsUtils.isWindows()) {
            if (OsUtils.is64Bit() && (Files.exists(Paths.get("./drivers/edgedriver-windows-64bit")) || Files.notExists(Paths.get("./drivers/edgedriver-windows-32bit")))) {
                return "drivers/edgedriver-windows-64bit";
            } else {
                return "drivers/edgedriver-windows-32bit";
            }
        }
        return null;
    }
There should be ".exe" suffix.

**Comment by andidev** [comment]
Yes that is true, I'll release a fix for this ASAP. 
Meanwhile you can manually set the driver path by annotating your test with 
'''java
@DriverPaths(edge="drivers/edgedriver-windows-64bit.exe")
'''

**Comment by andidev** [comment]
So I released the fix for this in version 2.5.1 and it should be available in maven repo within 24h. Did not test it since I don't have windows myself so if it does not work please comment this issue.

**Comment by andidev** [comment]
Sorry it should be version 3.5.1. Updated last comment
